s3_endpoint = "http://s3-mock:9000/kms"
object_folder = ["PUB-p1","PUB-p2","PUB-p3","PUB-p4"]

validator_addresses = ["http://kms-blockchain-validator:9090"]
http_validator_endpoints = ["http://kms-blockchain-validator:26657"]
kv_store_address = "http://kms-kv-store:8088"
faucet_address = "http://localhost:8000"

# TODO: update latest option to take latest asc contract and not just latest contract
# contract = "latest"
asc_address = "wasm18v47nqmhvejx3vc498pantg8vr435xa0rt6x0m6kzhp6yuqmcp8s9jfa9t"
mnemonic = "whisper stereo great helmet during hollow nominee skate frown daughter donor pool ozone few find risk cigar practice essay sketch rhythm novel dumb host"

# Address of the CSC
csc_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"
