[service]
listen_address = "0.0.0.0"
listen_port = 50051
timeout_secs = 360
# maximum grpc message size in bytes
grpc_max_message_size = 20971520 # 20 MiB

[tracing]
service_name = "kms-centralized"
endpoint = "http://localhost:4317"

[aws]
region = "us-east-1"
s3_endpoint = "http://s3-mock:9000"

[public_vault]
storage = "s3://kms"
storage_cache_size = 1000

[private_vault]
storage = "file://./keys"

# Optional rate limiting configuration.
# The `bucket_size` represents the total amount of tokens available for processing in the core.
# The fields other fields represents the price of each operation in the core. I.e. how many tokens will be taken while the operation is executing.
# If all tokens are in use then the core will refuse further operations until a sufficient amount of tokens are released.
[rate_limiter_conf]
bucket_size = 50000
dec = 1
reenc = 1
crsgen = 100
preproc = 5000
keygen = 1000
verify_proven_ct = 1