name: zama-kms-centralized
services:
  # KMS-Blockchain validator node
  setup-kms-blockchain-contracts:
    environment:
      - MODE=centralized

  # KMS-Core-centralized
  kms-core:
    container_name: ${DOCKER_COMPOSE_PROJECT}-kms-core
    image: ghcr.io/zama-ai/kms-service:${DOCKER_IMAGES_TAG}
    build:
      context: .
      dockerfile: core/service/operations/docker/dev.dockerfile
    ports:
      - "50051:50051"
    healthcheck:
      test: "grpc-health-probe --addr=localhost:50051"
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
    volumes:
      - kms_minio_secrets:/minio_secrets
      - ../core/service/config/:/app/kms/core/service/config
    depends_on:
      s3-mock-setup:
        condition: service_completed_successfully
    entrypoint: |
      /bin/sh -c " export AWS_ACCESS_KEY_ID=$$(cat /minio_secrets/access_key) &&
      export AWS_SECRET_ACCESS_KEY=$$(cat /minio_secrets/secret_key) &&
      echo 'Generating signing keys' && kms-gen-keys --pub-url s3://kms --aws-s3-endpoint http://s3-mock:9000 --aws-region us-east-1 --priv-url file://./keys --cmd signing-keys centralized &&
      echo 'Starting kms service' && kms-server --config-file config/compose_centralized.toml"

  kms-connector:
    container_name: ${DOCKER_COMPOSE_PROJECT}-kms-connector
    build:
      context: .
      dockerfile: blockchain/connector/operations/docker/dev.dockerfile
    image: ghcr.io/zama-ai/kms-blockchain-connector:${DOCKER_IMAGES_TAG}
    volumes:
      - ../blockchain/connector/config/:/app/kms-connector/config
    command:
      - "kms-blockchain-connector"
      - "--conf-file"
      - "config/centralized.toml"
    environment:
      - ASC_CONN__BLOCKCHAIN__ADDRESSES=http://kms-blockchain-validator:9090
      - ASC_CONN__CORE__ADDRESSES=http://kms-core:50051
      - ASC_CONN__STORE__URL=http://kms-kv-store:8088
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__RETRY_INTERVAL=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__RETRY_INTERVAL=1
    depends_on:
      kms-blockchain-validator:
        condition: service_healthy
      kms-core:
        condition: service_healthy
