services:
  setup-fhevm-coprocessor-db:
    container_name: ${DOCKER_COMPOSE_PROJECT}-setup-fhevm-coprocessor-db
    image: ghcr.io/zama-ai/fhevm-db-migration:e0fbcc6
    environment:
      DATABASE_URL: postgresql://postgres:postgres@${DOCKER_COMPOSE_PROJECT}-fhevm-coprocessor-db:5432/coprocessor
      TENANT_API_KEY: "a1503fb6-d79b-4e9e-826d-44cf262f3e05"
      ACL_CONTRACT_ADDRESS: "0x339EcE85B9E11a3A3AA557582784a15d7F82AAf2"
      INPUT_VERIFIER_ADDRESS: "0x69dE3158643e738a0724418b21a35FAA20CBb1c5"
    volumes:
      - ../network-fhe-keys/:/fhevm-keys/
    networks:
      - zama_default

networks:
  zama_default:
    external: true
